import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
// import CommonLayout from "../components/common/commonLayout"; import DbSidebar from "../components/common/DbSidebar";
import Breadcrumb from "../components/common/Breadcrumb";
import DbSidebar from "../components/common/DbSidebar";
;


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div className="max-w-[1320px] mx-auto p-5 mb-10 w-full">

            
            <div className="mb-5 text-center">
                <Breadcrumb title={"My-Dashboard"}/>
            </div>

            
            <div className="grid grid-cols-4 gap-5">

                
                <div className="col-span-1">
                    <DbSidebar />
                </div>

                
                <div className="col-span-3 p-4">
                    {children}
                </div>

            </div>

        </div>
    );
}
